### PR TITLE
Fix LXD not handling nic removal from openvswitch bridges

### LINKED ISSUE #3058: LXD Container fails to perform some VM actions with openvswitch NIC
**Description**
Open Nebula seems to try adding NIC to bridge before it's created (LXD). Problem is only present when rebooting an already made container. 

**To Reproduce**
* Create OpenVswitch bridge, mine looks like this:
```
bridge "ovsbr0"
        Port "one-11-0"
            Interface "one-11-0"
        Port "one-13-0"
            Interface "one-13-0"
        Port "eno1"
            Interface "eno1"
        Port "ovsbr0"
            Interface "ovsbr0"
                type: internal
        Port "one-10-0"
            Interface "one-10-0"
    ovs_version: "2.5.5"
```
* Create LXD container with attached NIC
* Container will boot just fine
* Reboot will fail with error:
```
Generating deployment file: /var/lib/one/vms/20/deployment.2
Mon Mar 11 10:45:17 2019 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_context.
Mon Mar 11 10:45:18 2019 [Z0][VMM][I]: Command execution fail: /var/tmp/one/vnm/ovswitch/pre PFZ...T4=
Mon Mar 11 10:45:18 2019 [Z0][VMM][I]: ovs-ofctl: ovsbr0: couldn't find port `one-20-0'
Mon Mar 11 10:45:18 2019 [Z0][VMM][E]: pre: Command "sudo ovs-ofctl del-flows ovsbr0 in_port=" failed.
Mon Mar 11 10:45:18 2019 [Z0][VMM][E]: pre: ovs-ofctl: 0/0: port value out of range for in_port
Mon Mar 11 10:45:18 2019 [Z0][VMM][E]: ovs-ofctl: 0/0: port value out of range for in_port
Mon Mar 11 10:45:18 2019 [Z0][VMM][E]: 
Mon Mar 11 10:45:18 2019 [Z0][VMM][I]: ExitCode: 1
Mon Mar 11 10:45:18 2019 [Z0][VMM][I]: Failed to execute network driver operation: pre.
Mon Mar 11 10:45:18 2019 [Z0][VMM][E]: Error deploying virtual machine: ovswitch: ovs-ofctl: 0/0: port value out of range for in_port
Mon Mar 11 10:45:18 2019 [Z0][VM][I]: New state is POWEROFF
```

**Expected behavior**
Re-creation/initialization of one-xx interface prior to attaching it to bridge so that boot is successful.

**Details**
 - Affected Component: LXD VMs
 - Hypervisor: LXD
```
# lxc version
Client version: 3.0.3
Server version: 3.0.3
```

**Additional context**
I've also had problems where ON would try to attach existing one-xx interface to bridge while it is already part of bridge. Error could be omitted but results in failed boot instead. I can create a separate issue for this if needed.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

### PR DESCRIPTION
**Pull request by dann1**
Unlike libvirt which handles the ports removal on nic detach action nad powerofss, LXD just handles nic port creation on start and nic attach. The drivers have been updated to remove ports on unhandled actions if nic matches ovswitch driver.

Fixes #3058

### CODE REVIEW

**Comment by dann1** [comment]
Applies to master as well

File: src/vmm_mad/remotes/lib/lxd/container.rb [hunk 1]
```diff
@@ -384,6 +390,21 @@ def vnc(signal)
 
     private
 
+    # Deletes the switch port. Unlike libvirt, LXD doesn't handle this.
```
Comment (rsmontero) [inline src/vmm_mad/remotes/lib/lxd/container.rb]: Add return type to method description

Be consistent in returning variables. This method returns String, Boolean or nil

File: src/vmm_mad/remotes/lib/lxd/container.rb [hunk 2]
```diff
@@ -177,6 +177,11 @@ def start(options = {})
 
     def stop(options = { :timeout => 120 })
         change_state(__method__, options)
+
```
Comment (rsmontero) [inline src/vmm_mad/remotes/lib/lxd/container.rb]: This should be called through the pre/post/clean scripts. This code should be moved to the owsirch network drivers
